// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package utils

import (
	"github.com/blang/semver"
)

var SdkVersion semver.Version = semver.Version{}
var pluginDownloadURL string = ""
